name = "FieldDicts"
uuid = "5ac04fe7-78fe-4eb3-ac2d-702565c067c7"
authors = ["Zachary P. Christensen <zchristensen7@gmail.com> and contributors"]
version = "0.1.2"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.8"

[targets]
test = ["Documenter", "Test"]
